language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.5.5
  - DJANGO=1.6.11
  - DJANGO=1.7.7
before_install:
  - export DJANGO_SETTINGS_MODULE=suit.tests.settings
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test suit
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.3
      env: DJANGO=1.4.5
    - python: 3.4
      env: DJANGO=1.4.5
    - python: 2.6
      env: DJANGO=1.6.5
    - python: 2.6
      env: DJANGO=1.7
    - python: pypy
      env: DJANGO=1.4.5

    # Fails. Django issue #19944
    # https://code.djangoproject.com/ticket/19944
    - python: pypy
      env: DJANGO=1.5
